# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d173309839a81e3bbac78bfefcf7a015837bcfcf410cf11362e99743a30dd28c3018bb65658fdd1622fd19cc301565e530736c3f38776357ea8909221d460887

test:
  secret_key_base: 32cc70ebc70c0088583320b1101c4521eac4f4056a188f5556b4444780d38a7d2e6fa1f43d58d5cd2cf503c9487cffd8e798f9ea75947cf3e3b9828262a1e348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
